code overhaul and move from YACL to MidnightLib
Luligabi1/MiningUtility pull request #8
Opened 2023-10-02 12:36 UTC by AmyMialee

2023-10-02 23:33 UTC, Luligabi1 commented on gradle.properties
> +midnightlib_version=1.4.1-fabric
Please revert all config related changes - I'd rather use only YACL and not rely on 3rd party libraries for the core config functionality.

2023-10-02 23:33 UTC, Luligabi1 requested changes
Check comment above

2023-10-03 10:20 UTC, AmyMialee commented
MidnightConfig.class is 1 class for the whole mod, you can copy the entire thing into your mod if you want (it's mentioned as a valid way to use it) and requires much less maintainance.
Especially when the old config system is like half the size of the whole mod.

2023-10-03 12:43 UTC, AmyMialee commented
also is YACL not a 3rd party library?

2023-10-03 14:12 UTC, Luligabi1 commented
> also is YACL not a 3rd party library?

Yes, but it's only used for the config screen on ModMenu; if it stops being/takes longer to be updated, it's not holding back any releases.

> MidnightConfig.class is 1 class for the whole mod, you can copy the entire thing into your mod if you want (it's mentioned as a valid way to use it)
> Especially when the old config system is like half the size of the whole mod.

It's not a principle of size.

> and requires much less maintainance

This particular config system has been used on a lot of Cafeteria's mods for over 3 years now and it hasn't required any maintenance whatsoever on that time period.

2024-12-02 12:38 UTC, closed without merging